import = [
  "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]
live_config_reload = true

# FiraCode Nerd Font
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 13

[window]
opacity = 0.98
